#!/usr/bin/env bash

REQUIRED_ENV_VARS=(
  AGGREGATOR_IMAGE
  SERVICE_BIND
  SERVICE_PORT
  POSTGRES_DB
  POSTGRES_USER
  POSTGRES_PASSWORD_HOST_FILE
)

REQUIRED_SECRET_PATH_VARS=(
  POSTGRES_PASSWORD_HOST_FILE
)
